name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Generating keystore
      run: |
        keytool -genkey -noprompt  -alias alias  -dname "CN=test.com, OU=test, O=test, L=test, S=test, C=IN"  -keystore test.keystore  -storepass password  -keypass password
        echo "storeFile=../test.keystore" > local.properties
        echo "keyAlias=alias" >> local.properties
        echo "storePassword=password" >> local.properties
        echo "keyPassword=password" >> local.properties
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
